<?php

namespace DoctrineProxies\__CG__\App\Models;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class GiftCardSettings extends \App\Models\GiftCardSettings implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'id', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'organizationId', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'organization', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'serial', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'stripeConnectId', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'stripeConnect', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'title', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'description', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'image', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'backgroundImage', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'colour', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'currency', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'modifiedAt', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'deletedAt', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'idPrettyfier'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'id', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'organizationId', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'organization', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'serial', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'stripeConnectId', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'stripeConnect', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'title', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'description', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'image', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'backgroundImage', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'colour', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'currency', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'modifiedAt', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'deletedAt', '' . "\0" . 'App\\Models\\GiftCardSettings' . "\0" . 'idPrettyfier'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (GiftCardSettings $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): \Ramsey\Uuid\UuidInterface
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getSerial(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerial', []);

        return parent::getSerial();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganizationId(): \Ramsey\Uuid\UuidInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganizationId', []);

        return parent::getOrganizationId();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganization(): \App\Models\Organization
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganization', []);

        return parent::getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    public function getStripeConnectId(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStripeConnectId', []);

        return parent::getStripeConnectId();
    }

    /**
     * {@inheritDoc}
     */
    public function getStripeConnect(): \App\Models\StripeConnect
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStripeConnect', []);

        return parent::getStripeConnect();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getImage(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function getBackgroundImage(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBackgroundImage', []);

        return parent::getBackgroundImage();
    }

    /**
     * {@inheritDoc}
     */
    public function getColour(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColour', []);

        return parent::getColour();
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrencyString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrencyString', []);

        return parent::getCurrencyString();
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency(): \Money\Currency
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', []);

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedAt', []);

        return parent::getModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedAt', []);

        return parent::getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrettyID(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrettyID', []);

        return parent::getPrettyID();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title): \App\Models\GiftCardSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Models\GiftCardSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(string $image): \App\Models\GiftCardSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function setBackgroundImage(string $backgroundImage): \App\Models\GiftCardSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBackgroundImage', [$backgroundImage]);

        return parent::setBackgroundImage($backgroundImage);
    }

    /**
     * {@inheritDoc}
     */
    public function setColour(string $colour): \App\Models\GiftCardSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColour', [$colour]);

        return parent::setColour($colour);
    }

    /**
     * {@inheritDoc}
     */
    public function setSerial(?string $serial): \App\Models\GiftCardSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerial', [$serial]);

        return parent::setSerial($serial);
    }

    /**
     * {@inheritDoc}
     */
    public function setStripeConnectId(string $stripeConnectId): \App\Models\GiftCardSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStripeConnectId', [$stripeConnectId]);

        return parent::setStripeConnectId($stripeConnectId);
    }

    /**
     * {@inheritDoc}
     */
    public function delete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'delete', []);

        return parent::delete();
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

}
