<?php

namespace DoctrineProxies\__CG__\App\Models\Loyalty;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LoyaltySecondary extends \App\Models\Loyalty\LoyaltySecondary implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltySecondary' . "\0" . 'id', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltySecondary' . "\0" . 'schemeId', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltySecondary' . "\0" . 'scheme', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltySecondary' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltySecondary' . "\0" . 'lastUsedAt', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltySecondary' . "\0" . 'deletedAt', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltySecondary' . "\0" . 'type', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltySecondary' . "\0" . 'serial'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltySecondary' . "\0" . 'id', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltySecondary' . "\0" . 'schemeId', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltySecondary' . "\0" . 'scheme', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltySecondary' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltySecondary' . "\0" . 'lastUsedAt', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltySecondary' . "\0" . 'deletedAt', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltySecondary' . "\0" . 'type', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltySecondary' . "\0" . 'serial'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LoyaltySecondary $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): \Ramsey\Uuid\UuidInterface
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getSchemeId(): \Ramsey\Uuid\UuidInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchemeId', []);

        return parent::getSchemeId();
    }

    /**
     * {@inheritDoc}
     */
    public function getScheme(): \App\Models\Loyalty\LoyaltyStampScheme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScheme', []);

        return parent::getScheme();
    }

    /**
     * {@inheritDoc}
     */
    public function isActive(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActive', []);

        return parent::isActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive(bool $isActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$isActive]);

        return parent::setActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastUsedAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastUsedAt', []);

        return parent::getLastUsedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function touch()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'touch', []);

        return parent::touch();
    }

    /**
     * {@inheritDoc}
     */
    public function setSerial(?string $serial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerial', [$serial]);

        return parent::setSerial($serial);
    }

    /**
     * {@inheritDoc}
     */
    public function getSerial(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerial', []);

        return parent::getSerial();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeepAppUrl(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeepAppUrl', []);

        return parent::getDeepAppUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

}
