<?php

namespace DoctrineProxies\__CG__\App\Models\WebTracking;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class WebsiteProfileCookies extends \App\Models\WebTracking\WebsiteProfileCookies implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteProfileCookies' . "\0" . 'cookieId', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteProfileCookies' . "\0" . 'profileId', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteProfileCookies' . "\0" . 'profile', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteProfileCookies' . "\0" . 'visits', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteProfileCookies' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteProfileCookies' . "\0" . 'lastvisitAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteProfileCookies' . "\0" . 'cookieId', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteProfileCookies' . "\0" . 'profileId', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteProfileCookies' . "\0" . 'profile', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteProfileCookies' . "\0" . 'visits', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteProfileCookies' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteProfileCookies' . "\0" . 'lastvisitAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (WebsiteProfileCookies $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCookieId(): string
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getCookieId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCookieId', []);

        return parent::getCookieId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCookieId(string $cookieId): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCookieId', [$cookieId]);

        return parent::setCookieId($cookieId);
    }

    /**
     * {@inheritDoc}
     */
    public function setProfileId(int $profileId): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfileId', [$profileId]);

        return parent::setProfileId($profileId);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisits(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisits', []);

        return parent::getVisits();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisits(int $visit): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisits', [$visit]);

        return parent::setVisits($visit);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfileId(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfileId', []);

        return parent::getProfileId();
    }

    /**
     * {@inheritDoc}
     */
    public function getProfile(): \App\Models\UserProfile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfile', []);

        return parent::getProfile();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastvisitAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastvisitAt', []);

        return parent::getLastvisitAt();
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

}
