<?php

namespace DoctrineProxies\__CG__\App\Models\Billing\Quotes;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Quotes extends \App\Models\Billing\Quotes\Quotes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);
        return parent::__get($name);
    }

    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

        return parent::__set($name, $value);
    }



    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Billing\\Quotes\\Quotes' . "\0" . 'id', '' . "\0" . 'App\\Models\\Billing\\Quotes\\Quotes' . "\0" . 'reseller', '' . "\0" . 'App\\Models\\Billing\\Quotes\\Quotes' . "\0" . 'resellerOrganizationId', '' . "\0" . 'App\\Models\\Billing\\Quotes\\Quotes' . "\0" . 'customer', '' . "\0" . 'App\\Models\\Billing\\Quotes\\Quotes' . "\0" . 'customerOrganizationId', '' . "\0" . 'App\\Models\\Billing\\Quotes\\Quotes' . "\0" . 'description', '' . "\0" . 'App\\Models\\Billing\\Quotes\\Quotes' . "\0" . 'payload', '' . "\0" . 'App\\Models\\Billing\\Quotes\\Quotes' . "\0" . 'hostedPage', '' . "\0" . 'App\\Models\\Billing\\Quotes\\Quotes' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\Billing\\Quotes\\Quotes' . "\0" . 'updatedAt', '' . "\0" . 'App\\Models\\Billing\\Quotes\\Quotes' . "\0" . 'expiresAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Billing\\Quotes\\Quotes' . "\0" . 'id', '' . "\0" . 'App\\Models\\Billing\\Quotes\\Quotes' . "\0" . 'reseller', '' . "\0" . 'App\\Models\\Billing\\Quotes\\Quotes' . "\0" . 'resellerOrganizationId', '' . "\0" . 'App\\Models\\Billing\\Quotes\\Quotes' . "\0" . 'customer', '' . "\0" . 'App\\Models\\Billing\\Quotes\\Quotes' . "\0" . 'customerOrganizationId', '' . "\0" . 'App\\Models\\Billing\\Quotes\\Quotes' . "\0" . 'description', '' . "\0" . 'App\\Models\\Billing\\Quotes\\Quotes' . "\0" . 'payload', '' . "\0" . 'App\\Models\\Billing\\Quotes\\Quotes' . "\0" . 'hostedPage', '' . "\0" . 'App\\Models\\Billing\\Quotes\\Quotes' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\Billing\\Quotes\\Quotes' . "\0" . 'updatedAt', '' . "\0" . 'App\\Models\\Billing\\Quotes\\Quotes' . "\0" . 'expiresAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Quotes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): string
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(string $id): \App\Models\Billing\Quotes\Quotes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getReseller(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReseller', []);

        return parent::getReseller();
    }

    /**
     * {@inheritDoc}
     */
    public function setReseller(string $reseller): \App\Models\Billing\Quotes\Quotes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReseller', [$reseller]);

        return parent::setReseller($reseller);
    }

    /**
     * {@inheritDoc}
     */
    public function getResellerOrganizationId(): \Ramsey\Uuid\UuidInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResellerOrganizationId', []);

        return parent::getResellerOrganizationId();
    }

    /**
     * {@inheritDoc}
     */
    public function setResellerOrganizationId(\Ramsey\Uuid\UuidInterface $resellerOrganizationId): \App\Models\Billing\Quotes\Quotes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResellerOrganizationId', [$resellerOrganizationId]);

        return parent::setResellerOrganizationId($resellerOrganizationId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomer(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomer', []);

        return parent::getCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomer(string $customer): \App\Models\Billing\Quotes\Quotes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomer', [$customer]);

        return parent::setCustomer($customer);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerOrganizationId(): \Ramsey\Uuid\UuidInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerOrganizationId', []);

        return parent::getCustomerOrganizationId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerOrganizationId(\Ramsey\Uuid\UuidInterface $customerOrganizationId): \App\Models\Billing\Quotes\Quotes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerOrganizationId', [$customerOrganizationId]);

        return parent::setCustomerOrganizationId($customerOrganizationId);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Models\Billing\Quotes\Quotes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayload(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayload', []);

        return parent::getPayload();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayload(string $payload): \App\Models\Billing\Quotes\Quotes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayload', [$payload]);

        return parent::setPayload($payload);
    }

    /**
     * {@inheritDoc}
     */
    public function getHostedPage(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHostedPage', []);

        return parent::getHostedPage();
    }

    /**
     * {@inheritDoc}
     */
    public function setHostedPage(string $hostedPage): \App\Models\Billing\Quotes\Quotes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHostedPage', [$hostedPage]);

        return parent::setHostedPage($hostedPage);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt): \App\Models\Billing\Quotes\Quotes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt): \App\Models\Billing\Quotes\Quotes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpiresAt(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpiresAt', []);

        return parent::getExpiresAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpiresAt(int $expiresAt): \App\Models\Billing\Quotes\Quotes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpiresAt', [$expiresAt]);

        return parent::setExpiresAt($expiresAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', []);

        return parent::getArrayCopy();
    }

}
