<?php

namespace DoctrineProxies\__CG__\App\Models;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class GiftCard extends \App\Models\GiftCard implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'id', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'organizationRegistrationId', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'organizationRegistration', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'giftCardSettingsId', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'giftCardSettings', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'organizationId', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'organization', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'transactionId', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'amount', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'currency', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'profileId', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'profile', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'activatedAt', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'redeemedBy', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'redeemedByUser', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'redeemedAt', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'refundedByUser', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'refundedBy', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'refundedAt', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'idPrettyfier', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'events'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'id', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'organizationRegistrationId', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'organizationRegistration', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'giftCardSettingsId', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'giftCardSettings', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'organizationId', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'organization', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'transactionId', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'amount', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'currency', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'profileId', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'profile', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'activatedAt', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'redeemedBy', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'redeemedByUser', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'redeemedAt', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'refundedByUser', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'refundedBy', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'refundedAt', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'idPrettyfier', '' . "\0" . 'App\\Models\\GiftCard' . "\0" . 'events'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (GiftCard $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): \Ramsey\Uuid\UuidInterface
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getGiftCardSettingsId(): \Ramsey\Uuid\UuidInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGiftCardSettingsId', []);

        return parent::getGiftCardSettingsId();
    }

    /**
     * {@inheritDoc}
     */
    public function getGiftCardSettings(): \App\Models\GiftCardSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGiftCardSettings', []);

        return parent::getGiftCardSettings();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganizationId(): \Ramsey\Uuid\UuidInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganizationId', []);

        return parent::getOrganizationId();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganization(): \App\Models\Organization
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganization', []);

        return parent::getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    public function getTransactionId(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransactionId', []);

        return parent::getTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    public function getAmount(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmount', []);

        return parent::getAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', []);

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function getProfileId(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfileId', []);

        return parent::getProfileId();
    }

    /**
     * {@inheritDoc}
     */
    public function getProfile(): \App\Models\UserProfile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfile', []);

        return parent::getProfile();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getActivatedAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivatedAt', []);

        return parent::getActivatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getRedeemedAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRedeemedAt', []);

        return parent::getRedeemedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getRedeemedBy(): ?\App\Models\OauthUser
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRedeemedBy', []);

        return parent::getRedeemedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function getRedeemedById(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRedeemedById', []);

        return parent::getRedeemedById();
    }

    /**
     * {@inheritDoc}
     */
    public function getRefundedByUser(): ?\App\Models\OauthUser
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefundedByUser', []);

        return parent::getRefundedByUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getRefundedBy(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefundedBy', []);

        return parent::getRefundedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function getRefundedAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefundedAt', []);

        return parent::getRefundedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function humanID(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'humanID', []);

        return parent::humanID();
    }

    /**
     * {@inheritDoc}
     */
    public function changeOwner(\App\Models\UserProfile $profile): \App\Models\GiftCard
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'changeOwner', [$profile]);

        return parent::changeOwner($profile);
    }

    /**
     * {@inheritDoc}
     */
    public function redeem(\App\Models\OauthUser $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'redeem', [$user]);

        return parent::redeem($user);
    }

    /**
     * {@inheritDoc}
     */
    public function refund(\App\Models\OauthUser $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'refund', [$user]);

        return parent::refund($user);
    }

    /**
     * {@inheritDoc}
     */
    public function activate(string $transactionId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'activate', [$transactionId]);

        return parent::activate($transactionId);
    }

    /**
     * {@inheritDoc}
     */
    public function description(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'description', []);

        return parent::description();
    }

    /**
     * {@inheritDoc}
     */
    public function status(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'status', []);

        return parent::status();
    }

    /**
     * {@inheritDoc}
     */
    public function formattedCurrency(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'formattedCurrency', []);

        return parent::formattedCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function feePercentage(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'feePercentage', []);

        return parent::feePercentage();
    }

    /**
     * {@inheritDoc}
     */
    public function fee(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fee', []);

        return parent::fee();
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

    /**
     * {@inheritDoc}
     */
    public function stripeDetails(string $token): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'stripeDetails', [$token]);

        return parent::stripeDetails($token);
    }

    /**
     * {@inheritDoc}
     */
    public function emailSendTo(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'emailSendTo', []);

        return parent::emailSendTo();
    }

    /**
     * {@inheritDoc}
     */
    public function emailDetails(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'emailDetails', []);

        return parent::emailDetails();
    }

    /**
     * {@inheritDoc}
     */
    public function qrCodeURI(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'qrCodeURI', []);

        return parent::qrCodeURI();
    }

    /**
     * {@inheritDoc}
     */
    public function flushEvents(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'flushEvents', []);

        parent::flushEvents();
    }

}
