<?php

namespace DoctrineProxies\__CG__\App\Models;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MarketingMessages extends \App\Models\MarketingMessages implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);
        return parent::__get($name);
    }

    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

        return parent::__set($name, $value);
    }



    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'id', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'created', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'subject', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'name', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'smsContents', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'emailContents', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'emailContentsJson', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'smsSender', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'sendToSms', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'sendToEmail', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'deleted', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'admin', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'organizationId', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'templateType'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'id', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'created', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'subject', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'name', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'smsContents', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'emailContents', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'emailContentsJson', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'smsSender', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'sendToSms', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'sendToEmail', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'deleted', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'admin', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'organizationId', '' . "\0" . 'App\\Models\\MarketingMessages' . "\0" . 'templateType'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MarketingMessages $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getOrganizationId(): \Ramsey\Uuid\UuidInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganizationId', []);

        return parent::getOrganizationId();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): string
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getSmsContents(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSmsContents', []);

        return parent::getSmsContents();
    }

    /**
     * {@inheritDoc}
     */
    public function getSmsSender(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSmsSender', []);

        return parent::getSmsSender();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailContents(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailContents', []);

        return parent::getEmailContents();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailContentsJson(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailContentsJson', []);

        return parent::getEmailContentsJson();
    }

    /**
     * {@inheritDoc}
     */
    public function getSendToSms(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSendToSms', []);

        return parent::getSendToSms();
    }

    /**
     * {@inheritDoc}
     */
    public function getSendToEmail(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSendToEmail', []);

        return parent::getSendToEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getSubject(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubject', []);

        return parent::getSubject();
    }

    /**
     * {@inheritDoc}
     */
    public function getTemplateType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTemplateType', []);

        return parent::getTemplateType();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted(bool $deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', [$deleted]);

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

    /**
     * {@inheritDoc}
     */
    public function touch()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'touch', []);

        return parent::touch();
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', []);

        return parent::getArrayCopy();
    }

}
