<?php

namespace DoctrineProxies\__CG__\App\Models\Reviews;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ReviewSettings extends \App\Models\Reviews\ReviewSettings implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'id', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'organizationId', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'organization', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'editedAt', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'deletedAt', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'subject', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'sendAfterSecs', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'headerImage', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'backgroundImage', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'titleText', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'bodyText', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'textAlignment', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'isActive', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'serial', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'facebookPageId', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'happyOrNot', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'googlePageId', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'tripadvisorUrl', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'templateId', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'template'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'id', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'organizationId', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'organization', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'editedAt', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'deletedAt', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'subject', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'sendAfterSecs', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'headerImage', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'backgroundImage', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'titleText', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'bodyText', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'textAlignment', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'isActive', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'serial', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'facebookPageId', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'happyOrNot', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'googlePageId', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'tripadvisorUrl', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'templateId', '' . "\0" . 'App\\Models\\Reviews\\ReviewSettings' . "\0" . 'template'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ReviewSettings $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function updateFromArray(array $data): \App\Models\Reviews\ReviewSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateFromArray', [$data]);

        return parent::updateFromArray($data);
    }

    /**
     * {@inheritDoc}
     */
    public function touch()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'touch', []);

        return parent::touch();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubject(?string $subject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubject', [$subject]);

        return parent::setSubject($subject);
    }

    /**
     * {@inheritDoc}
     */
    public function setSendAfterSeconds(int $sendAfterSeconds = 86400)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSendAfterSeconds', [$sendAfterSeconds]);

        return parent::setSendAfterSeconds($sendAfterSeconds);
    }

    /**
     * {@inheritDoc}
     */
    public function setHeaderImage(string $headerImage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeaderImage', [$headerImage]);

        return parent::setHeaderImage($headerImage);
    }

    /**
     * {@inheritDoc}
     */
    public function setBackgroundImage(?string $backgroundImage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBackgroundImage', [$backgroundImage]);

        return parent::setBackgroundImage($backgroundImage);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleText(string $titleText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleText', [$titleText]);

        return parent::setTitleText($titleText);
    }

    /**
     * {@inheritDoc}
     */
    public function setBodyText(string $bodyText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBodyText', [$bodyText]);

        return parent::setBodyText($bodyText);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive(bool $isActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', [$isActive]);

        return parent::setIsActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function setHappyOrNot(bool $happyOrNot)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHappyOrNot', [$happyOrNot]);

        return parent::setHappyOrNot($happyOrNot);
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebookPageId(?string $facebookPageId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebookPageId', [$facebookPageId]);

        return parent::setFacebookPageId($facebookPageId);
    }

    /**
     * {@inheritDoc}
     */
    public function setTripadvisorUrl(?string $tripadvisorUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTripadvisorUrl', [$tripadvisorUrl]);

        return parent::setTripadvisorUrl($tripadvisorUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function setGooglePageId(?string $googlePageId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGooglePageId', [$googlePageId]);

        return parent::setGooglePageId($googlePageId);
    }

    /**
     * {@inheritDoc}
     */
    public function setTextAlignment(string $textAlignment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTextAlignment', [$textAlignment]);

        return parent::setTextAlignment($textAlignment);
    }

    /**
     * {@inheritDoc}
     */
    public function setSenderSettings(?array $template)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenderSettings', [$template]);

        return parent::setSenderSettings($template);
    }

    /**
     * {@inheritDoc}
     */
    public function setTemplate(\App\Models\Marketing\TemplateSettings $template)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTemplate', [$template]);

        return parent::setTemplate($template);
    }

    /**
     * {@inheritDoc}
     */
    public function setTemplateId(string $templateId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTemplateId', [$templateId]);

        return parent::setTemplateId($templateId);
    }

    /**
     * {@inheritDoc}
     */
    public function setSerial(?string $serial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerial', [$serial]);

        return parent::setSerial($serial);
    }

    /**
     * {@inheritDoc}
     */
    public function setSendAfterSecs(?int $sendAfterSecs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSendAfterSecs', [$sendAfterSecs]);

        return parent::setSendAfterSecs($sendAfterSecs);
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted(bool $isDeleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', [$isDeleted]);

        return parent::setDeleted($isDeleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): \Ramsey\Uuid\UuidInterface
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTemplateId(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTemplateId', []);

        return parent::getTemplateId();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganization(): \App\Models\Organization
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganization', []);

        return parent::getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    public function getSerial(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerial', []);

        return parent::getSerial();
    }

    /**
     * {@inheritDoc}
     */
    public function getTripadvisorUrl(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTripadvisorUrl', []);

        return parent::getTripadvisorUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function getTripadvisorReviewLink(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTripadvisorReviewLink', []);

        return parent::getTripadvisorReviewLink();
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebookPageId(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebookPageId', []);

        return parent::getFacebookPageId();
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebookReviewLink(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebookReviewLink', []);

        return parent::getFacebookReviewLink();
    }

    /**
     * {@inheritDoc}
     */
    public function getGooglePlaceId(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGooglePlaceId', []);

        return parent::getGooglePlaceId();
    }

    /**
     * {@inheritDoc}
     */
    public function getGoogleReviewLink(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGoogleReviewLink', []);

        return parent::getGoogleReviewLink();
    }

    /**
     * {@inheritDoc}
     */
    public function getSubject(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubject', []);

        return parent::getSubject();
    }

    /**
     * {@inheritDoc}
     */
    public function getSendAfterSecs(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSendAfterSecs', []);

        return parent::getSendAfterSecs();
    }

    /**
     * {@inheritDoc}
     */
    public function getSendTime(): \DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSendTime', []);

        return parent::getSendTime();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganizationId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganizationId', []);

        return parent::getOrganizationId();
    }

    /**
     * {@inheritDoc}
     */
    public function reviewStarLinks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'reviewStarLinks', []);

        return parent::reviewStarLinks();
    }

    /**
     * {@inheritDoc}
     */
    public function emailArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'emailArray', []);

        return parent::emailArray();
    }

    /**
     * {@inheritDoc}
     */
    public function hasValidSubscription(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasValidSubscription', []);

        return parent::hasValidSubscription();
    }

    /**
     * {@inheritDoc}
     */
    public function getHappyOrNot(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHappyOrNot', []);

        return parent::getHappyOrNot();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', []);

        return parent::getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

}
