<?php

namespace DoctrineProxies\__CG__\App\Models\Forms;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Forms extends \App\Models\Forms\Forms implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'id', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'organizationId', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'organization', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'name', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'redirect', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'inputs', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'serials', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'colour', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'optText', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'deletedAt', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'validSubscription'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'id', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'organizationId', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'organization', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'name', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'redirect', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'inputs', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'serials', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'colour', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'optText', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'deletedAt', '' . "\0" . 'App\\Models\\Forms\\Forms' . "\0" . 'validSubscription'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Forms $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setName(string $name): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setColour(string $color): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColour', [$color]);

        return parent::setColour($color);
    }

    /**
     * {@inheritDoc}
     */
    public function setOptText(string $text): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOptText', [$text]);

        return parent::setOptText($text);
    }

    /**
     * {@inheritDoc}
     */
    public function setInputs(array $inputs): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputs', [$inputs]);

        return parent::setInputs($inputs);
    }

    /**
     * {@inheritDoc}
     */
    public function setSerials(array $serials): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerials', [$serials]);

        return parent::setSerials($serials);
    }

    /**
     * {@inheritDoc}
     */
    public function setRedirect(string $redirect): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRedirect', [$redirect]);

        return parent::setRedirect($redirect);
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted(bool $deleted): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', [$deleted]);

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): \Ramsey\Uuid\UuidInterface
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getRedirect(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRedirect', []);

        return parent::getRedirect();
    }

    /**
     * {@inheritDoc}
     */
    public function getColour(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColour', []);

        return parent::getColour();
    }

    /**
     * {@inheritDoc}
     */
    public function getOptText(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptText', []);

        return parent::getOptText();
    }

    /**
     * {@inheritDoc}
     */
    public function getInputs(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputs', []);

        return parent::getInputs();
    }

    /**
     * {@inheritDoc}
     */
    public function getSerials(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerials', []);

        return parent::getSerials();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganizationId(): \Ramsey\Uuid\UuidInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganizationId', []);

        return parent::getOrganizationId();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganization(): \App\Models\Organization
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganization', []);

        return parent::getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidSubscription(bool $validSubscription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidSubscription', [$validSubscription]);

        return parent::setValidSubscription($validSubscription);
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

}
