<?php

namespace DoctrineProxies\__CG__\App\Models\Reviews;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserReview extends \App\Models\Reviews\UserReview implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'id', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'organizationRegistrationId', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'organizationRegistration', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'reviewSettingsId', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'reviewSettings', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'organizationId', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'organization', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'profileId', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'profile', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'keywords', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'review', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'platform', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'rating', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'sentiment', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'scorePositive', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'scoreNegative', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'scoreMixed', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'scoreNeutral', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'metadata', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'doneAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'id', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'organizationRegistrationId', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'organizationRegistration', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'reviewSettingsId', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'reviewSettings', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'organizationId', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'organization', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'profileId', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'profile', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'keywords', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'review', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'platform', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'rating', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'sentiment', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'scorePositive', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'scoreNegative', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'scoreMixed', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'scoreNeutral', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'metadata', '' . "\0" . 'App\\Models\\Reviews\\UserReview' . "\0" . 'doneAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UserReview $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setSentimentFromAwsComprehend(array $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSentimentFromAwsComprehend', [$data]);

        return parent::setSentimentFromAwsComprehend($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfile(): ?\App\Models\UserProfile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfile', []);

        return parent::getProfile();
    }

    /**
     * {@inheritDoc}
     */
    public function getSettings(): \App\Models\Reviews\ReviewSettings
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSettings', []);

        return parent::getSettings();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): \Ramsey\Uuid\UuidInterface
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getReview(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReview', []);

        return parent::getReview();
    }

    /**
     * {@inheritDoc}
     */
    public function canReviewAtThisTime(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'canReviewAtThisTime', []);

        return parent::canReviewAtThisTime();
    }

    /**
     * {@inheritDoc}
     */
    public function getKeywords()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKeywords', []);

        return parent::getKeywords();
    }

    /**
     * {@inheritDoc}
     */
    public function setDone(bool $done)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDone', [$done]);

        return parent::setDone($done);
    }

    /**
     * {@inheritDoc}
     */
    public function getDone(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDone', []);

        return parent::getDone();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAtFromString(string $date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAtFromString', [$date]);

        return parent::setCreatedAtFromString($date);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$date]);

        return parent::setCreatedAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

}
