<?php

namespace DoctrineProxies\__CG__\App\Models;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserProfile extends \App\Models\UserProfile implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);
        return parent::__get($name);
    }

    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

        return parent::__set($name, $value);
    }



    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'id', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'email', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'first', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'last', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'phone', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'phonecc', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'postcode', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'postcodeValid', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'phoneValid', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'opt', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'age', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'birthMonth', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'birthDay', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'ageRange', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'gender', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'verified', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'verified_id', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'timestamp', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'lat', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'lng', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'updated', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'country', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'countryCode', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'custom'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'id', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'email', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'first', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'last', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'phone', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'phonecc', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'postcode', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'postcodeValid', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'phoneValid', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'opt', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'age', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'birthMonth', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'birthDay', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'ageRange', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'gender', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'verified', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'verified_id', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'timestamp', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'lat', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'lng', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'updated', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'country', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'countryCode', '' . "\0" . 'App\\Models\\UserProfile' . "\0" . 'custom'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UserProfile $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getFirst(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirst', []);

        return parent::getFirst();
    }

    /**
     * {@inheritDoc}
     */
    public function getLast(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLast', []);

        return parent::getLast();
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function getPhonecc(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhonecc', []);

        return parent::getPhonecc();
    }

    /**
     * {@inheritDoc}
     */
    public function getPostcode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostcode', []);

        return parent::getPostcode();
    }

    /**
     * {@inheritDoc}
     */
    public function isPostcodeValid(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPostcodeValid', []);

        return parent::isPostcodeValid();
    }

    /**
     * {@inheritDoc}
     */
    public function isPhoneValid(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPhoneValid', []);

        return parent::isPhoneValid();
    }

    /**
     * {@inheritDoc}
     */
    public function getOpt(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpt', []);

        return parent::getOpt();
    }

    /**
     * {@inheritDoc}
     */
    public function getAge(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAge', []);

        return parent::getAge();
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthMonth(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthMonth', []);

        return parent::getBirthMonth();
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthDay(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthDay', []);

        return parent::getBirthDay();
    }

    /**
     * {@inheritDoc}
     */
    public function getAgeRange(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgeRange', []);

        return parent::getAgeRange();
    }

    /**
     * {@inheritDoc}
     */
    public function getGender(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', []);

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function getVerified(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVerified', []);

        return parent::getVerified();
    }

    /**
     * {@inheritDoc}
     */
    public function getVerifiedId(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVerifiedId', []);

        return parent::getVerifiedId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTimestamp(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimestamp', []);

        return parent::getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    public function getLat(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLat', []);

        return parent::getLat();
    }

    /**
     * {@inheritDoc}
     */
    public function getLng(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLng', []);

        return parent::getLng();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', []);

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function getCountryCode(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountryCode', []);

        return parent::getCountryCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getFullName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullName', []);

        return parent::getFullName();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Models\UserProfile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustom(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustom', []);

        return parent::getCustom();
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomForSerial(string $serial): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomForSerial', [$serial]);

        return parent::getCustomForSerial($serial);
    }

    /**
     * {@inheritDoc}
     */
    public function setCustom(array $custom): \App\Models\UserProfile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustom', [$custom]);

        return parent::setCustom($custom);
    }

    /**
     * {@inheritDoc}
     */
    public function setFirst(string $first): \App\Models\UserProfile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirst', [$first]);

        return parent::setFirst($first);
    }

    /**
     * {@inheritDoc}
     */
    public function setLast(string $last): \App\Models\UserProfile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLast', [$last]);

        return parent::setLast($last);
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone(?string $phone): \App\Models\UserProfile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthMonth(?int $birthMonth): \App\Models\UserProfile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthMonth', [$birthMonth]);

        return parent::setBirthMonth($birthMonth);
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthDay(?int $birthDay): \App\Models\UserProfile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthDay', [$birthDay]);

        return parent::setBirthDay($birthDay);
    }

    /**
     * {@inheritDoc}
     */
    public function setGender(?string $gender): \App\Models\UserProfile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', [$gender]);

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function setTimestamp(\DateTime $timestamp): \App\Models\UserProfile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimestamp', [$timestamp]);

        return parent::setTimestamp($timestamp);
    }

    /**
     * {@inheritDoc}
     */
    public function setVerifiedId(string $verified_id): \App\Models\UserProfile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVerifiedId', [$verified_id]);

        return parent::setVerifiedId($verified_id);
    }

    /**
     * {@inheritDoc}
     */
    public function validate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'validate', []);

        return parent::validate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated(\DateTime $updated): \App\Models\UserProfile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', [$updated]);

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function emailSendTo(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'emailSendTo', []);

        return parent::emailSendTo();
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

    /**
     * {@inheritDoc}
     */
    public function zapierSerialize(string $serial = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'zapierSerialize', [$serial]);

        return parent::zapierSerialize($serial);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', []);

        return parent::getArrayCopy();
    }

}
