<?php

namespace DoctrineProxies\__CG__\App\Models;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserRegistration extends \App\Models\UserRegistration implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\UserRegistration' . "\0" . 'serial', '' . "\0" . 'App\\Models\\UserRegistration' . "\0" . 'profileId', '' . "\0" . 'App\\Models\\UserRegistration' . "\0" . 'numberOfVisits', '' . "\0" . 'App\\Models\\UserRegistration' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\UserRegistration' . "\0" . 'lastSeenAt', '' . "\0" . 'App\\Models\\UserRegistration' . "\0" . 'emailOptInDate', '' . "\0" . 'App\\Models\\UserRegistration' . "\0" . 'smsOptInDate', '' . "\0" . 'App\\Models\\UserRegistration' . "\0" . 'locationOptInDate'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\UserRegistration' . "\0" . 'serial', '' . "\0" . 'App\\Models\\UserRegistration' . "\0" . 'profileId', '' . "\0" . 'App\\Models\\UserRegistration' . "\0" . 'numberOfVisits', '' . "\0" . 'App\\Models\\UserRegistration' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\UserRegistration' . "\0" . 'lastSeenAt', '' . "\0" . 'App\\Models\\UserRegistration' . "\0" . 'emailOptInDate', '' . "\0" . 'App\\Models\\UserRegistration' . "\0" . 'smsOptInDate', '' . "\0" . 'App\\Models\\UserRegistration' . "\0" . 'locationOptInDate'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UserRegistration $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSerial(): string
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getSerial();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerial', []);

        return parent::getSerial();
    }

    /**
     * {@inheritDoc}
     */
    public function getProfileId(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfileId', []);

        return parent::getProfileId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberOfVisits(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberOfVisits', []);

        return parent::getNumberOfVisits();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastSeenAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastSeenAt', []);

        return parent::getLastSeenAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailOptInDate(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailOptInDate', []);

        return parent::getEmailOptInDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailOptInDate(?\DateTime $emailOptInDate): \App\Models\UserRegistration
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailOptInDate', [$emailOptInDate]);

        return parent::setEmailOptInDate($emailOptInDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getSmsOptInDate(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSmsOptInDate', []);

        return parent::getSmsOptInDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setSmsOptInDate(?\DateTime $smsOptInDate): \App\Models\UserRegistration
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSmsOptInDate', [$smsOptInDate]);

        return parent::setSmsOptInDate($smsOptInDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocationOptInDate(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocationOptInDate', []);

        return parent::getLocationOptInDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocationOptInDate(?\DateTime $locationOptInDate): \App\Models\UserRegistration
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocationOptInDate', [$locationOptInDate]);

        return parent::setLocationOptInDate($locationOptInDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getSMSOptOut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSMSOptOut', []);

        return parent::getSMSOptOut();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailOptOut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailOptOut', []);

        return parent::getEmailOptOut();
    }

    /**
     * {@inheritDoc}
     */
    public function getLocationOptOut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocationOptOut', []);

        return parent::getLocationOptOut();
    }

}
