<?php

namespace DoctrineProxies\__CG__\App\Models\DataSources;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Interaction extends \App\Models\DataSources\Interaction implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\DataSources\\Interaction' . "\0" . 'id', '' . "\0" . 'App\\Models\\DataSources\\Interaction' . "\0" . 'organizationId', '' . "\0" . 'App\\Models\\DataSources\\Interaction' . "\0" . 'organization', '' . "\0" . 'App\\Models\\DataSources\\Interaction' . "\0" . 'dataSourceId', '' . "\0" . 'App\\Models\\DataSources\\Interaction' . "\0" . 'dataSource', '' . "\0" . 'App\\Models\\DataSources\\Interaction' . "\0" . 'profiles', '' . "\0" . 'App\\Models\\DataSources\\Interaction' . "\0" . 'serials', '' . "\0" . 'App\\Models\\DataSources\\Interaction' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\DataSources\\Interaction' . "\0" . 'endedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\DataSources\\Interaction' . "\0" . 'id', '' . "\0" . 'App\\Models\\DataSources\\Interaction' . "\0" . 'organizationId', '' . "\0" . 'App\\Models\\DataSources\\Interaction' . "\0" . 'organization', '' . "\0" . 'App\\Models\\DataSources\\Interaction' . "\0" . 'dataSourceId', '' . "\0" . 'App\\Models\\DataSources\\Interaction' . "\0" . 'dataSource', '' . "\0" . 'App\\Models\\DataSources\\Interaction' . "\0" . 'profiles', '' . "\0" . 'App\\Models\\DataSources\\Interaction' . "\0" . 'serials', '' . "\0" . 'App\\Models\\DataSources\\Interaction' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\DataSources\\Interaction' . "\0" . 'endedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Interaction $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): \Ramsey\Uuid\UuidInterface
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganizationId(): \Ramsey\Uuid\UuidInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganizationId', []);

        return parent::getOrganizationId();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganization(): \App\Models\Organization
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganization', []);

        return parent::getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataSourceId(): \Ramsey\Uuid\UuidInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataSourceId', []);

        return parent::getDataSourceId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataSource(): \App\Models\DataSources\DataSource
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataSource', []);

        return parent::getDataSource();
    }

    /**
     * {@inheritDoc}
     */
    public function addProfile(\App\Models\UserProfile $userProfile): \App\Models\DataSources\Interaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProfile', [$userProfile]);

        return parent::addProfile($userProfile);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfiles', []);

        return parent::getProfiles();
    }

    /**
     * {@inheritDoc}
     */
    public function addLocation(\App\Models\Locations\LocationSettings $locationSettings): \App\Models\DataSources\Interaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLocation', [$locationSettings]);

        return parent::addLocation($locationSettings);
    }

    /**
     * {@inheritDoc}
     */
    public function getSerials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerials', []);

        return parent::getSerials();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getEndedAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndedAt', []);

        return parent::getEndedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function end()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'end', []);

        return parent::end();
    }

    /**
     * {@inheritDoc}
     */
    public function length(): ?\DateInterval
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'length', []);

        return parent::length();
    }

    /**
     * {@inheritDoc}
     */
    public function lengthSeconds(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'lengthSeconds', []);

        return parent::lengthSeconds();
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

}
