<?php

namespace DoctrineProxies\__CG__\App\Models\Members;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CustomerPricing extends \App\Models\Members\CustomerPricing implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);
        return parent::__get($name);
    }

    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

        return parent::__set($name, $value);
    }



    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'uid', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'organizationId', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'organization', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'lite', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'medium', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'premium', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'starter', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'allIn', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'reviews', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'reviewsCreditAllocation', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'unifiApHosting', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'unifiHosting', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'contentFilter', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'marketingAutomation', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'marketingAutomationCreditAllocation', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'customIntegration', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'stories'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'uid', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'organizationId', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'organization', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'lite', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'medium', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'premium', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'starter', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'allIn', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'reviews', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'reviewsCreditAllocation', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'unifiApHosting', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'unifiHosting', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'contentFilter', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'marketingAutomation', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'marketingAutomationCreditAllocation', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'customIntegration', '' . "\0" . 'App\\Models\\Members\\CustomerPricing' . "\0" . 'stories'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CustomerPricing $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', []);

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function getUid(): string
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getUid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUid', []);

        return parent::getUid();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganizationId(): \Ramsey\Uuid\UuidInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganizationId', []);

        return parent::getOrganizationId();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganization(): \App\Models\Organization
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganization', []);

        return parent::getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    public function getLite(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLite', []);

        return parent::getLite();
    }

    /**
     * {@inheritDoc}
     */
    public function getMedium(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedium', []);

        return parent::getMedium();
    }

    /**
     * {@inheritDoc}
     */
    public function getPremium(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPremium', []);

        return parent::getPremium();
    }

    /**
     * {@inheritDoc}
     */
    public function getStarter(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStarter', []);

        return parent::getStarter();
    }

    /**
     * {@inheritDoc}
     */
    public function getAllIn(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllIn', []);

        return parent::getAllIn();
    }

    /**
     * {@inheritDoc}
     */
    public function getReviews(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReviews', []);

        return parent::getReviews();
    }

    /**
     * {@inheritDoc}
     */
    public function getReviewsCreditAllocation(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReviewsCreditAllocation', []);

        return parent::getReviewsCreditAllocation();
    }

    /**
     * {@inheritDoc}
     */
    public function getUnifiApHosting(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnifiApHosting', []);

        return parent::getUnifiApHosting();
    }

    /**
     * {@inheritDoc}
     */
    public function getUnifiHosting(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnifiHosting', []);

        return parent::getUnifiHosting();
    }

    /**
     * {@inheritDoc}
     */
    public function getContentFilter(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentFilter', []);

        return parent::getContentFilter();
    }

    /**
     * {@inheritDoc}
     */
    public function getMarketingAutomation(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarketingAutomation', []);

        return parent::getMarketingAutomation();
    }

    /**
     * {@inheritDoc}
     */
    public function getMarketingAutomationCreditAllocation(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarketingAutomationCreditAllocation', []);

        return parent::getMarketingAutomationCreditAllocation();
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomIntegration(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomIntegration', []);

        return parent::getCustomIntegration();
    }

    /**
     * {@inheritDoc}
     */
    public function getStories(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStories', []);

        return parent::getStories();
    }

}
