<?php

namespace DoctrineProxies\__CG__\App\Models\Loyalty;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LoyaltyStampScheme extends \App\Models\Loyalty\LoyaltyStampScheme implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'id', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'organizationId', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'organization', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'rewardId', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'reward', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'serial', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'requiredStamps', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'terms', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'stampCooldownDuration', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'backgroundColour', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'foregroundColour', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'labelColour', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'labelIcon', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'icon', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'backgroundImage', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'isActive', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'isDefault', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'editedAt', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'deletedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'id', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'organizationId', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'organization', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'rewardId', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'reward', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'serial', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'requiredStamps', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'terms', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'stampCooldownDuration', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'backgroundColour', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'foregroundColour', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'labelColour', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'labelIcon', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'icon', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'backgroundImage', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'isActive', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'isDefault', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'editedAt', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampScheme' . "\0" . 'deletedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LoyaltyStampScheme $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): \Ramsey\Uuid\UuidInterface
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganizationId(): \Ramsey\Uuid\UuidInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganizationId', []);

        return parent::getOrganizationId();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganization(): \App\Models\Organization
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganization', []);

        return parent::getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    public function getRewardId(): \Ramsey\Uuid\UuidInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRewardId', []);

        return parent::getRewardId();
    }

    /**
     * {@inheritDoc}
     */
    public function getReward(): \App\Models\Loyalty\LoyaltyReward
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReward', []);

        return parent::getReward();
    }

    /**
     * {@inheritDoc}
     */
    public function getSerial(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerial', []);

        return parent::getSerial();
    }

    /**
     * {@inheritDoc}
     */
    public function getRequiredStamps(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequiredStamps', []);

        return parent::getRequiredStamps();
    }

    /**
     * {@inheritDoc}
     */
    public function getStampCooldownDuration(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStampCooldownDuration', []);

        return parent::getStampCooldownDuration();
    }

    /**
     * {@inheritDoc}
     */
    public function getTerms(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTerms', []);

        return parent::getTerms();
    }

    /**
     * {@inheritDoc}
     */
    public function getBackgroundColour(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBackgroundColour', []);

        return parent::getBackgroundColour();
    }

    /**
     * {@inheritDoc}
     */
    public function getForegroundColour(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getForegroundColour', []);

        return parent::getForegroundColour();
    }

    /**
     * {@inheritDoc}
     */
    public function getLabelColour(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabelColour', []);

        return parent::getLabelColour();
    }

    /**
     * {@inheritDoc}
     */
    public function getIcon(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIcon', []);

        return parent::getIcon();
    }

    /**
     * {@inheritDoc}
     */
    public function getLabelIcon(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabelIcon', []);

        return parent::getLabelIcon();
    }

    /**
     * {@inheritDoc}
     */
    public function getBackgroundImage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBackgroundImage', []);

        return parent::getBackgroundImage();
    }

    /**
     * {@inheritDoc}
     */
    public function isActive(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActive', []);

        return parent::isActive();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDefault(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDefault', []);

        return parent::getIsDefault();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getEditedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEditedAt', []);

        return parent::getEditedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedAt', []);

        return parent::getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function delete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'delete', []);

        return parent::delete();
    }

    /**
     * {@inheritDoc}
     */
    public function updateFromArray(array $data): \App\Models\Loyalty\LoyaltyStampScheme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateFromArray', [$data]);

        return parent::updateFromArray($data);
    }

    /**
     * {@inheritDoc}
     */
    public function setTerms(?string $terms): \App\Models\Loyalty\LoyaltyStampScheme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTerms', [$terms]);

        return parent::setTerms($terms);
    }

    /**
     * {@inheritDoc}
     */
    public function setStampCooldownDuration(string $stampCooldownDuration): \App\Models\Loyalty\LoyaltyStampScheme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStampCooldownDuration', [$stampCooldownDuration]);

        return parent::setStampCooldownDuration($stampCooldownDuration);
    }

    /**
     * {@inheritDoc}
     */
    public function setBackgroundColour(string $backgroundColour): \App\Models\Loyalty\LoyaltyStampScheme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBackgroundColour', [$backgroundColour]);

        return parent::setBackgroundColour($backgroundColour);
    }

    /**
     * {@inheritDoc}
     */
    public function setForegroundColour(string $foregroundColour): \App\Models\Loyalty\LoyaltyStampScheme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setForegroundColour', [$foregroundColour]);

        return parent::setForegroundColour($foregroundColour);
    }

    /**
     * {@inheritDoc}
     */
    public function setLabelColour(string $labelColour): \App\Models\Loyalty\LoyaltyStampScheme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabelColour', [$labelColour]);

        return parent::setLabelColour($labelColour);
    }

    /**
     * {@inheritDoc}
     */
    public function setLabelIcon(string $labelIcon): \App\Models\Loyalty\LoyaltyStampScheme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabelIcon', [$labelIcon]);

        return parent::setLabelIcon($labelIcon);
    }

    /**
     * {@inheritDoc}
     */
    public function setIcon(string $icon): \App\Models\Loyalty\LoyaltyStampScheme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIcon', [$icon]);

        return parent::setIcon($icon);
    }

    /**
     * {@inheritDoc}
     */
    public function setBackgroundImage(string $backgroundImage): \App\Models\Loyalty\LoyaltyStampScheme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBackgroundImage', [$backgroundImage]);

        return parent::setBackgroundImage($backgroundImage);
    }

    /**
     * {@inheritDoc}
     */
    public function setSerial(string $serial): \App\Models\Loyalty\LoyaltyStampScheme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerial', [$serial]);

        return parent::setSerial($serial);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive(bool $isActive): \App\Models\Loyalty\LoyaltyStampScheme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', [$isActive]);

        return parent::setIsActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDefault(bool $isDefault): \App\Models\Loyalty\LoyaltyStampScheme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDefault', [$isDefault]);

        return parent::setIsDefault($isDefault);
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

}
