<?php

namespace DoctrineProxies\__CG__\App\Models\Loyalty;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LoyaltyStampCard extends \App\Models\Loyalty\LoyaltyStampCard implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'id', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'schemeId', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'scheme', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'profileId', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'profile', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'collectedStamps', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'events', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'activatedAt', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'lastStampedAt', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'redeemedAt', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'deletedAt', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'eventNotifier', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'organizationRegistrationId', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'organizationRegistration'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'id', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'schemeId', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'scheme', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'profileId', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'profile', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'collectedStamps', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'events', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'activatedAt', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'lastStampedAt', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'redeemedAt', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'deletedAt', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'eventNotifier', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'organizationRegistrationId', '' . "\0" . 'App\\Models\\Loyalty\\LoyaltyStampCard' . "\0" . 'organizationRegistration'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LoyaltyStampCard $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): \Ramsey\Uuid\UuidInterface
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getSchemeId(): \Ramsey\Uuid\UuidInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchemeId', []);

        return parent::getSchemeId();
    }

    /**
     * {@inheritDoc}
     */
    public function getScheme(): \App\Models\Loyalty\LoyaltyStampScheme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScheme', []);

        return parent::getScheme();
    }

    /**
     * {@inheritDoc}
     */
    public function getProfileId(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfileId', []);

        return parent::getProfileId();
    }

    /**
     * {@inheritDoc}
     */
    public function getProfile(): \App\Models\UserProfile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfile', []);

        return parent::getProfile();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventNotifier(\App\Package\Loyalty\Events\EventNotifier $eventNotifier): \App\Models\Loyalty\LoyaltyStampCard
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventNotifier', [$eventNotifier]);

        return parent::setEventNotifier($eventNotifier);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvents(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvents', []);

        return parent::getEvents();
    }

    /**
     * {@inheritDoc}
     */
    public function getCollectedStamps(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCollectedStamps', []);

        return parent::getCollectedStamps();
    }

    /**
     * {@inheritDoc}
     */
    public function getRemainingStamps(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemainingStamps', []);

        return parent::getRemainingStamps();
    }

    /**
     * {@inheritDoc}
     */
    public function isFull(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFull', []);

        return parent::isFull();
    }

    /**
     * {@inheritDoc}
     */
    public function canStampAtThisTime(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'canStampAtThisTime', []);

        return parent::canStampAtThisTime();
    }

    /**
     * {@inheritDoc}
     */
    public function stamp(\App\Package\Loyalty\Stamps\StampContext $context, int $stamps = 1): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'stamp', [$context, $stamps]);

        parent::stamp($context, $stamps);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastStampedAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastStampedAt', []);

        return parent::getLastStampedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getActivatedAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivatedAt', []);

        return parent::getActivatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function isActivated(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActivated', []);

        return parent::isActivated();
    }

    /**
     * {@inheritDoc}
     */
    public function activate(\App\Models\OauthUser $activator = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'activate', [$activator]);

        return parent::activate($activator);
    }

    /**
     * {@inheritDoc}
     */
    public function getRedeemedAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRedeemedAt', []);

        return parent::getRedeemedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function isRedeemed(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isRedeemed', []);

        return parent::isRedeemed();
    }

    /**
     * {@inheritDoc}
     */
    public function redeem(\App\Models\OauthUser $redeemer = NULL): \App\Models\Loyalty\LoyaltyReward
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'redeem', [$redeemer]);

        return parent::redeem($redeemer);
    }

    /**
     * {@inheritDoc}
     */
    public function flush(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'flush', []);

        parent::flush();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedAt', []);

        return parent::getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function isDeleted(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDeleted', []);

        return parent::isDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function delete(\App\Models\OauthUser $deleter = NULL): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'delete', [$deleter]);

        parent::delete($deleter);
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

}
