<?php

namespace DoctrineProxies\__CG__\App\Models\WebTracking;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class WebsiteEvent extends \App\Models\WebTracking\WebsiteEvent implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteEvent' . "\0" . 'id', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteEvent' . "\0" . 'websiteId', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteEvent' . "\0" . 'website', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteEvent' . "\0" . 'cookieId', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteEvent' . "\0" . 'eventType', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteEvent' . "\0" . 'pagePath', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteEvent' . "\0" . 'referralPath', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteEvent' . "\0" . 'createdAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteEvent' . "\0" . 'id', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteEvent' . "\0" . 'websiteId', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteEvent' . "\0" . 'website', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteEvent' . "\0" . 'cookieId', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteEvent' . "\0" . 'eventType', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteEvent' . "\0" . 'pagePath', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteEvent' . "\0" . 'referralPath', '' . "\0" . 'App\\Models\\WebTracking\\WebsiteEvent' . "\0" . 'createdAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (WebsiteEvent $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): \Ramsey\Uuid\UuidInterface
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEventType(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventType', []);

        return parent::getEventType();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getCookieId(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCookieId', []);

        return parent::getCookieId();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsiteId(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsiteId', []);

        return parent::getWebsiteId();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsite(): \App\Models\WebTracking\Website
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsite', []);

        return parent::getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function getPagePath(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagePath', []);

        return parent::getPagePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getPageReferral(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageReferral', []);

        return parent::getPageReferral();
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

}
