<?php

namespace DoctrineProxies\__CG__\App\Models\DataSources;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OrganizationRegistration extends \App\Models\DataSources\OrganizationRegistration implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\DataSources\\OrganizationRegistration' . "\0" . 'id', '' . "\0" . 'App\\Models\\DataSources\\OrganizationRegistration' . "\0" . 'organizationId', '' . "\0" . 'App\\Models\\DataSources\\OrganizationRegistration' . "\0" . 'organization', '' . "\0" . 'App\\Models\\DataSources\\OrganizationRegistration' . "\0" . 'profileId', '' . "\0" . 'App\\Models\\DataSources\\OrganizationRegistration' . "\0" . 'profile', '' . "\0" . 'App\\Models\\DataSources\\OrganizationRegistration' . "\0" . 'registrations', '' . "\0" . 'App\\Models\\DataSources\\OrganizationRegistration' . "\0" . 'lastInteractedAt', '' . "\0" . 'App\\Models\\DataSources\\OrganizationRegistration' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\DataSources\\OrganizationRegistration' . "\0" . 'dataOptInAt', '' . "\0" . 'App\\Models\\DataSources\\OrganizationRegistration' . "\0" . 'smsOptInAt', '' . "\0" . 'App\\Models\\DataSources\\OrganizationRegistration' . "\0" . 'emailOptInAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\DataSources\\OrganizationRegistration' . "\0" . 'id', '' . "\0" . 'App\\Models\\DataSources\\OrganizationRegistration' . "\0" . 'organizationId', '' . "\0" . 'App\\Models\\DataSources\\OrganizationRegistration' . "\0" . 'organization', '' . "\0" . 'App\\Models\\DataSources\\OrganizationRegistration' . "\0" . 'profileId', '' . "\0" . 'App\\Models\\DataSources\\OrganizationRegistration' . "\0" . 'profile', '' . "\0" . 'App\\Models\\DataSources\\OrganizationRegistration' . "\0" . 'registrations', '' . "\0" . 'App\\Models\\DataSources\\OrganizationRegistration' . "\0" . 'lastInteractedAt', '' . "\0" . 'App\\Models\\DataSources\\OrganizationRegistration' . "\0" . 'createdAt', '' . "\0" . 'App\\Models\\DataSources\\OrganizationRegistration' . "\0" . 'dataOptInAt', '' . "\0" . 'App\\Models\\DataSources\\OrganizationRegistration' . "\0" . 'smsOptInAt', '' . "\0" . 'App\\Models\\DataSources\\OrganizationRegistration' . "\0" . 'emailOptInAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (OrganizationRegistration $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): \Ramsey\Uuid\UuidInterface
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganizationId(): \Ramsey\Uuid\UuidInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganizationId', []);

        return parent::getOrganizationId();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganization(): \App\Models\Organization
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganization', []);

        return parent::getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    public function getProfileId(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfileId', []);

        return parent::getProfileId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataOptIn(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataOptIn', []);

        return parent::getDataOptIn();
    }

    /**
     * {@inheritDoc}
     */
    public function getSmsOptIn(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSmsOptIn', []);

        return parent::getSmsOptIn();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailOptIn(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailOptIn', []);

        return parent::getEmailOptIn();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataOptIn(bool $optIn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataOptIn', [$optIn]);

        return parent::setDataOptIn($optIn);
    }

    /**
     * {@inheritDoc}
     */
    public function setSmsOptIn(bool $optIn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSmsOptIn', [$optIn]);

        return parent::setSmsOptIn($optIn);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailOptIn(bool $optIn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailOptIn', [$optIn]);

        return parent::setEmailOptIn($optIn);
    }

    /**
     * {@inheritDoc}
     */
    public function setProfile(\App\Models\UserProfile $profile): \App\Models\DataSources\OrganizationRegistration
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfile', [$profile]);

        return parent::setProfile($profile);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfile(): \App\Models\UserProfile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfile', []);

        return parent::getProfile();
    }

    /**
     * {@inheritDoc}
     */
    public function trackRegistrationSource(\App\Models\DataSources\DataSource $dataSource, string $serial, int $interactions = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'trackRegistrationSource', [$dataSource, $serial, $interactions]);

        return parent::trackRegistrationSource($dataSource, $serial, $interactions);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistrations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistrations', []);

        return parent::getRegistrations();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastInteractedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastInteractedAt', []);

        return parent::getLastInteractedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

}
